# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User')),
            ],
        ),
        migrations.CreateModel(
            name='Meetup_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.Meetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User')),
            ],
        ),
        migrations.CreateModel(
            name='Meetup_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.Meetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User')),
            ],
        ),
        migrations.CreateModel(
            name='Messageboard_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messageboard_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User')),
            ],
        ),
        migrations.AddField(
            model_name='messageboard_comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.Messageboard_Message'),
        ),
        migrations.AddField(
            model_name='messageboard_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPNAME.User'),
        ),
    ]
