# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup_Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_bookmarks', to='APPNAME.Meetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_bookmarks', to='APPNAME.User')),
            ],
        ),
    ]
