# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0003_meetup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
