# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0004_auto_20170719_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='detail',
            new_name='details',
        ),
    ]
