# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0006_auto_20170719_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
