# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0007_auto_20170719_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='APPNAME.User'),
        ),
        migrations.AlterField(
            model_name='meetup_comment',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_comments', to='APPNAME.Meetup'),
        ),
        migrations.AlterField(
            model_name='meetup_like',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_likes', to='APPNAME.Meetup'),
        ),
        migrations.AlterField(
            model_name='meetup_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_likes', to='APPNAME.User'),
        ),
        migrations.AlterField(
            model_name='messageboard_comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_comments', to='APPNAME.Messageboard_Message'),
        ),
        migrations.AlterField(
            model_name='messageboard_message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_messages', to='APPNAME.User'),
        ),
    ]
