# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0009_auto_20170719_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageboard_Comment_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messageboard_Message_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messageboard_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_likes', to='APPNAME.Messageboard_Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_likes', to='APPNAME.User')),
            ],
        ),
        migrations.RenameField(
            model_name='messageboard_comment',
            old_name='message',
            new_name='messageboard_message',
        ),
        migrations.AddField(
            model_name='messageboard_comment_like',
            name='messageboard_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_comment_likes', to='APPNAME.Messageboard_Comment'),
        ),
        migrations.AddField(
            model_name='messageboard_comment_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_comment_likes', to='APPNAME.User'),
        ),
    ]
