# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0010_auto_20170719_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard_comment_like',
            name='messageboard_comment',
        ),
        migrations.RemoveField(
            model_name='messageboard_comment_like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messageboard_message_like',
            name='messageboard_message',
        ),
        migrations.RemoveField(
            model_name='messageboard_message_like',
            name='user',
        ),
        migrations.AddField(
            model_name='messageboard_message',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Messageboard_Comment_Like',
        ),
        migrations.DeleteModel(
            name='Messageboard_Message_Like',
        ),
    ]
