# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0011_auto_20170724_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageboard_Message_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messageboard_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_views', to='APPNAME.Messageboard_Message')),
            ],
        ),
        migrations.AddField(
            model_name='meetup_like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup_like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
