# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0013_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(null=True, upload_to='picture'),
        ),
    ]
