# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0015_auto_20170725_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(null=True, upload_to='picture'),
        ),
    ]
