# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0019_auto_20170726_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='messageboard_message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='messageboard_message'),
        ),
    ]
