# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0021_messageboard_message_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
