# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0023_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageboard_Message_Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messageboard_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_bookmark', to='APPNAME.Messageboard_Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_bookmark', to='APPNAME.User')),
            ],
        ),
    ]
