# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0024_messageboard_message_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard_message_bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageboard_message_bookmarks', to='APPNAME.User'),
        ),
    ]
